services:
  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql

  kafka:
    image: confluentinc/cp-kafka:7.6.1
    container_name: kafka
    restart: always
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka:9092'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:9093'
      KAFKA_LISTENERS: 'PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_LOG_DIRS: '/tmp/kraft-combined-logs'
      CLUSTER_ID: 'MkU3OEVBNTcwNTJENDM2Qk'

  user-manager:
    build:
      context: .
      dockerfile: user-manager/Dockerfile
    container_name: user-manager
    restart: always
    expose:
      - "5000"
      - "50051"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgresql://user:password@postgres:5432/userdb
    volumes:
      - ./user-manager:/app
      - ./protos:/app/protos

  data-collector:
    build:
      context: .
      dockerfile: data-collector/Dockerfile
    container_name: data-collector
    restart: always
    expose:
      - "5001"
      - "50052"
    depends_on:
      - postgres
      - kafka
    environment:
      DATABASE_URL: postgresql://user:password@postgres:5432/datadb
      OPENSKY_CLIENT_ID: ${OPENSKY_CLIENT_ID}
      OPENSKY_CLIENT_SECRET: ${OPENSKY_CLIENT_SECRET}
    volumes:
      - ./data-collector:/app
      - ./protos:/app/protos

  alert-system:
    build:
      context: ./alert-system
      dockerfile: Dockerfile
    container_name: alert-system
    restart: always
    depends_on:
      - kafka
      - postgres
    environment:
      DATABASE_URL: postgresql://user:password@postgres:5432/datadb
      PYTHONUNBUFFERED: 1
    volumes:
      - ./alert-system:/app

  alert-notifier-system:
    build:
      context: ./alert-notifier-system
      dockerfile: Dockerfile
    container_name: alert-notifier-system
    restart: always
    depends_on:
      - kafka
    environment:
      PYTHONUNBUFFERED: 1
      SMTP_PASSWORD: ${SMTP_PASSWORD}
    volumes:
      - ./alert-notifier-system:/app

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - user-manager
      - data-collector

volumes:
  postgres_data:
