services:
  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql

  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "to-alert-system:1:1,to-notifier:1:1"
    depends_on:
      - zookeeper

  user-manager:
    build:
      context: .
      dockerfile: user-manager/Dockerfile
    container_name: user-manager
    restart: always
    ports:
      - "5000:5000"
      - "50051:50051"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgresql://user:password@postgres:5432/userdb
    volumes:
      - ./user-manager:/app
      - ./protos:/app/protos

  data-collector:
    build:
      context: .
      dockerfile: data-collector/Dockerfile
    container_name: data-collector
    restart: always
    ports:
      - "5001:5001"
      - "50052:50052"
    depends_on:
      - postgres
      - kafka
    environment:
      DATABASE_URL: postgresql://user:password@postgres:5432/datadb
    volumes:
      - ./data-collector:/app
      - ./protos:/app/protos

  alert-system:
    build:
      context: ./alert-system
      dockerfile: Dockerfile
    container_name: alert-system
    restart: always
    depends_on:
      - kafka
      - postgres
    environment:
      DATABASE_URL: postgresql://user:password@postgres:5432/datadb
      PYTHONUNBUFFERED: 1
    volumes:
      - ./alert-system:/app

  alert-notifier-system:
    build:
      context: ./alert-notifier-system
      dockerfile: Dockerfile
    container_name: alert-notifier-system
    restart: always
    depends_on:
      - kafka
    environment:
      PYTHONUNBUFFERED: 1
    volumes:
      - ./alert-notifier-system:/app

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - user-manager
      - data-collector

volumes:
  postgres_data:
