apiVersion: apps/v1
kind: Deployment
metadata:
  name: alert-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alert-system
  template:
    metadata:
      labels:
        app: alert-system
    spec:
      containers:
      - name: alert-system
        image: alert-system:latest
        imagePullPolicy: Never
        env:
        - name: DATABASE_URL
          value: "postgresql://user:password@postgres:5432/datadb"
        - name: PYTHONUNBUFFERED
          value: "1"
