apiVersion: apps/v1
kind: Deployment
metadata:
  name: alert-notifier-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alert-notifier-system
  template:
    metadata:
      labels:
        app: alert-notifier-system
    spec:
      containers:
      - name: alert-notifier-system
        image: alert-notifier-system:latest
        imagePullPolicy: Never
        env:
        - name: PYTHONUNBUFFERED
          value: "1"
        - name: SMTP_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: SMTP_PASSWORD
              optional: true
